In [8]:
# Read Fashion MNIST dataset

import util_mnist_reader 
import numpy as np
import scipy
import tensorflow.contrib.keras as keras
import tensorflow as tf
np.random.seed(123)
tf.set_random_seed(123)



X_train, y_train = util_mnist_reader.load_mnist('.', kind='train')

X_test, y_test = util_mnist_reader.load_mnist('.', kind='t10k')
#This is to load the dataset provided


mean_vals = np.mean(X_train, axis=0)
std_val = np.std(X_train)

X_train_centered = (X_train - mean_vals)/std_val
X_test_centered = (X_test - mean_vals)/std_val
#We center the dataset to make the algorithm run more efficiently/faster
#We take the transpose to get it into the shape 10 by 6,0000 so we have have each sample as its own column instead of its own row.

y_train_onehot = keras.utils.to_categorical(y_train)
#WITH TENSORFLOW WE CAN DO ONE_HOT_ENCODING IN ONE LINE!!
print('First 3 labels: ', y_train[:3])
print('\nFirst 3 labels (one-hot):\n', y_train_onehot[:3])

First 3 labels:  [9 0 0]

First 3 labels (one-hot):
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [9]:

import tensorflow.contrib.keras as keras

np.random.seed(123)
tf.set_random_seed(123)


model = keras.models.Sequential()


# add input layer
model.add(keras.layers.Dense(
    units=50,
    input_dim=X_train_centered.shape[1],
    kernel_initializer='glorot_uniform',
    bias_initializer='zeros',
    activation='tanh') 
)
# add hidden layer
model.add(
    keras.layers.Dense(
        units=50,
        input_dim=50,
        kernel_initializer='glorot_uniform',
        bias_initializer='zeros',
        activation='tanh')
    )
# add output layer
model.add(
    keras.layers.Dense(
        units=y_train_onehot.shape[1],
        input_dim=50,
        kernel_initializer='glorot_uniform',
        bias_initializer='zeros',
        activation='softmax')
    )

# define SGD optimizer
sgd_optimizer = keras.optimizers.SGD(
    lr=0.001, decay=1e-7, momentum=0.9
)
# compile model
model.compile(
    optimizer=sgd_optimizer,
    loss='categorical_crossentropy'
)



Instructions for updating:
Colocations handled automatically by placer.


In [10]:
history = model.fit(
    X_train_centered, y_train_onehot,
    batch_size=64, epochs=50,
    verbose=1, validation_split=0.1
)

Train on 54000 samples, validate on 6000 samples
Instructions for updating:
Use tf.cast instead.
Epoch 1/50
54000/54000 [==============================] - 5s 84us/sample - loss: 0.7978 - val_loss: 0.5587
Epoch 2/50
54000/54000 [==============================] - 3s 58us/sample - loss: 0.5138 - val_loss: 0.4786
Epoch 3/50
54000/54000 [==============================] - 3s 61us/sample - loss: 0.4571 - val_loss: 0.4446
Epoch 4/50
54000/54000 [==============================] - 3s 50us/sample - loss: 0.4267 - val_loss: 0.4229
Epoch 5/50
54000/54000 [==============================] - 3s 54us/sample - loss: 0.4058 - val_loss: 0.4043
Epoch 6/50
54000/54000 [==============================] - 3s 62us/sample - loss: 0.3901 - val_loss: 0.3949
Epoch 7/50
54000/54000 [==============================] - 3s 57us/sample - loss: 0.3772 - val_loss: 0.3856
Epoch 8/50
54000/54000 [==============================] - 3s 50us/sample - loss: 0.3661 - val_loss: 0.3797
Epoch 9/50
54000/54000 [=======================

In [11]:
y_train_pred = model.predict_classes(X_train_centered, verbose=0)
print('First 3 predictions: ', y_train_pred[:3])

First 3 predictions:  [9 0 0]


In [12]:
y_train_pred = model.predict_classes(X_train_centered, verbose=0)
correct_preds = np.sum(y_train == y_train_pred, axis=0)
train_acc = correct_preds / y_train.shape[0]

print(f'Training accuracy: {(train_acc * 100):.2f}')

# calculate testing accuracy
y_test_pred = model.predict_classes(X_test_centered, verbose=0)
correct_preds = np.sum(y_test == y_test_pred, axis=0)
test_acc = correct_preds / y_test.shape[0]

print(f'Test accuracy: {(test_acc * 100):.2f}')

Training accuracy: 92.77
Test accuracy: 87.36


[0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]