In [16]:
import util_mnist_reader 
import numpy as np
import scipy
from copy import copy, deepcopy


X_train, y_train = util_mnist_reader.load_mnist('.', kind='train')

X_test, y_test = util_mnist_reader.load_mnist('.', kind='t10k')
#This is to load the dataset provided

In [17]:
#reshape data to fit model
X_train = X_train.reshape(60000,28,28,1)
X_test = X_test.reshape(10000,28,28,1)
print(X_train.shape)


(60000, 28, 28, 1)


In [18]:
from keras.utils import to_categorical
#one-hot encode target column
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)


In [19]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten
#create model
model = Sequential()
#add model layers
model.add(Conv2D(64, kernel_size=3, activation= 'relu', input_shape=(28,28,1)))
model.add(Conv2D(32, kernel_size=3, activation= 'relu'))
model.add(Flatten())
model.add(Dense(10, activation = 'softmax' ))

In [21]:
#compile model using accuracy to measure model performance
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [22]:
#train the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=3)

Instructions for updating:
Use tf.cast instead.
Train on 60000 samples, validate on 10000 samples
Epoch 1/3
60000/60000 [==============================] - 128s 2ms/step - loss: 0.7195 - acc: 0.8199 - val_loss: 0.4109 - val_acc: 0.8527
Epoch 2/3
60000/60000 [==============================] - 125s 2ms/step - loss: 0.3355 - acc: 0.8781 - val_loss: 0.3721 - val_acc: 0.8682
Epoch 3/3
60000/60000 [==============================] - 129s 2ms/step - loss: 0.2788 - acc: 0.8976 - val_loss: 0.3638 - val_acc: 0.8718


In [27]:
#predict first 4 images in the test set
y_dummy = model.predict(X_test[:4])
y_dummy = np.round(y_dummy)
print(y_dummy)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [30]:
np.sum(y_dummy - y_test[:4])

0.0

In [ ]:
#PERFECT MATCHING!!!!! AWESOME